dist: trusty
sudo: false
language: php
php:
- 7.2
- 7.3
env:
  global:
  - WP_VERSION=latest WP_MULTISITE=0
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
cache:
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
before_deploy:
- npm run zip
- ls -la snow-monkey-archive-content.zip
- export RELEASE_FILE=$(ls snow-monkey-archive-content.zip)
deploy:
  provider: releases
  api_key:
    secure: hJAo+Rh4/AaN/5UhEX8Eah2EFU5iRT3FGB+TDJReDgBmeUf8P/2cD+9usmp8irfiOjKDvyyywx+d7bTtLaQ05+VZZRo6QOWTSNJImGgKEuNOEq1qfIkFcrU4An6aofKENne8yDAi3TC/R5fdf+2lhXM3Vef+mmdEMeJksY+Q80u1647+BWllkEVylvTPugfU1F65SqvcDHfkE7xS21Locv+MqJ7IxkuHplVOIZle45QY80gl/DIR+uu0dPKhZcy16/Dh/7c54N2ffgbXPszClRnwX53EoT7H4oSWJKEZMinODjZdjuSfv7hZlnxzOUdtjbgybwNizsBRZx8zlF4A/bSNNF4HUNrXav0/vR3jvkzCb1M7ft0gMZarwbwSkBfwk78IVCe9b/BXxYLdaJYymZoS82pTxJLhJxcTAystDz9uG8SE77ExtXCjg5f7adfIuWiRZYpfZbXnk2mCNmfTcOXRcxf6P/bs4ZeqYT1V92oeaxeRNiFe5YoSY1evEBz/0SQi9blDt45IS4xqRR0nv2S9LsPDSYN0cmIcGgPMuky2Tb86JtG3AUlUgZhBsaNzRExseUdxpQQNUmw/M7AvFxEvoagOkDms+tDrmR7PJToO5nILH8SZnvKRcEPJUVu8dGkwneO0vCcCS7Vb6xRIrpTsKju4ZJ/pk3iwPTDtbU0=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.3
    repo: inc2734/snow-monkey-archive-content
